import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
function notFound(res) { res.writeHead(404, {'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'}); fs.createReadStream(path.join(root,'404.html')).pipe(res); }
const types = { '.html':'text/html; charset=utf-8', '.css':'text/css; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.svg':'image/svg+xml', '.png':'image/png', '.webp':'image/webp', '.jpg':'image/jpeg', '.json':'application/json; charset=utf-8' };
http.createServer((req,res) => {
  let pathname; try { pathname = decodeURIComponent(new URL(req.url,'http://localhost').pathname); } catch { res.writeHead(400).end(); return; }
  const relative = pathname === '/' ? 'index.html' : /^\/privacy\/?$/.test(pathname) ? 'privacy/index.html' : /^\/consent\/?$/.test(pathname) ? 'consent/index.html' : /^\/products\/enamels\/?$/.test(pathname) ? 'products/enamels/index.html' : /^\/products\/hardeners\/?$/.test(pathname) ? 'products/hardeners/index.html' : /^\/products\/thinners\/?$/.test(pathname) ? 'products/thinners/index.html' : /^\/products\/kits\/?$/.test(pathname) ? 'products/kits/index.html' : /^\/colors\/eggplant-107\/?$/.test(pathname) ? 'colors/eggplant-107/index.html' : /^\/where-to-buy\/?$/.test(pathname) ? 'where-to-buy/index.html' : /^\/dealers\/?$/.test(pathname) ? 'dealers/index.html' : /^\/marketplaces\/?$/.test(pathname) ? 'marketplaces/index.html' : /^\/contacts\/?$/.test(pathname) ? 'contacts/index.html' :  /^\/reviews\/?$/.test(pathname) ? 'reviews/index.html' : /^\/partners\/?$/.test(pathname) ? 'partners/index.html' : /^\/concept\/?$/.test(pathname) ? 'concept.html' : /^\/about\/?$/.test(pathname) ? 'about/index.html' : /^\/how-to-paint\/?$/.test(pathname) ? 'how-to-paint/index.html' : /^\/colors\/?$/.test(pathname) ? 'colors/index.html' : /^\/products\/acrylic-enamel\/?$/.test(pathname) ? 'products/acrylic-enamel/index.html' : /^\/products\/?$/.test(pathname) ? 'products/index.html' : pathname.replace(/^\/+/, '');
  const file = path.resolve(root, relative);
  if (!file.startsWith(root + path.sep) || !['index.html','404.html','not-found.css','privacy/index.html','consent/index.html','privacy-ui.css','privacy-ui.js','homepage-refinement.css','styles.css','pages.css','dealers.js','products/enamels/index.html','products/hardeners/index.html','products/thinners/index.html','products/kits/index.html','colors/eggplant-107/index.html','dealers/index.html','where-to-buy/index.html','marketplaces/index.html','contacts/index.html','reviews/index.html','reviews/data.json','reviews.css','reviews.js','navigation.css','partners.css','partners/index.html','glass.css','refinement.css','art-direction.css','product-style.css','catalog.css','colors.css','colors/index.html','guide.css','how-to-paint/index.html','about.css','about/index.html','detail.css','products/acrylic-enamel/index.html','products/index.html','app.js','visual-refresh.css','concept.html','concept.css','concept.js','concept-motion.css','motion-runtime.js','site-art.css','site-art.js','motion-performance.css','homepage-previous.html'].includes(relative) && !relative.startsWith('assets/')) { notFound(res); return; }
  fs.stat(file,(err, stat) => { if(err || !stat.isFile()){ notFound(res); return; } res.writeHead(200,{'Content-Type':types[path.extname(file)] || 'application/octet-stream','Cache-Control':'no-cache'}); fs.createReadStream(file).pipe(res); });
}).listen(4187,'127.0.0.1',()=>console.log('Glosaniko local preview: http://127.0.0.1:4187'));
